AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Uptime Monitor
Metadata:
  AWS::ServerlessRepo::Application:
    Name: serverless-uptime-monitor
    Description: Monitors an HTTP endpoint's availability with AWS Lambda and CloudWatch
    Author: Fernando Dingler
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['uptime', 'monitoring', 'http', 'ping', 'website monitoring', 'availability', 'status']
    HomePageUrl: https://github.com/ferdingler/lambda-watchtower
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/ferdingler/lambda-watchtower

Globals:
  Function:
    Timeout: 30

Parameters:
  TargetUrl:
    Type: String
    Default: https://www.aws.amazon.com
  TargetName:
    Type: String
  CloudWatchNamespace:
    Type: String
    Default: Watchtower
  Timeout:
    Type: Number
    Default: 2000
  Frequency:
    Type: String
    Default: rate(1 minute)
    AllowedValues:
      - rate(1 minute)
      - rate(5 minutes)

Resources:
  WatchTowerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: '*'
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: 
              !Sub |
                {
                  "targets": [
                    {
                      "url": "${TargetUrl}",
                      "name": "${TargetName}"
                    }
                  ],
                  "namespace": "${CloudWatchNamespace}",
                  "timings": ["readable", "total", "lookup", "secureConnect", "close", "connect"],
                  "timeout": ${Timeout}
                }